import { Component } from '@angular/core';
import { ActivityShort } from '../activity-short/activity-short';
import { ActivityInfo } from '../activity';

@Component({
  selector: 'app-activity',
  imports: [ActivityShort],
  templateUrl: './activity.html',
  styleUrl: './activity.scss',
})
export class Activity {
  readonly baseUrl = 'https://angular.dev/assets/images/tutorials/common';

  activityList: ActivityInfo[] = [
    {
      id: 'uuid id 1',
      userId: 'uuid user id 1',
      provider: 'Strava',
      providerId: 'uuid Strava 1',
      name: 'Running 1',
      sportType: 'Running',
      distance: 5032,
      movingTime: 1234567,
      elapsedTime: 1234568,
      elevationGain: 17,
      maxSpeed: 10,
      averageHour: 8,
      maxHour: 10,
      calories: 500,
      date: '20:04 03.08.2026',
      photoUrl: `default_01.webp`,
      visibility: true,
      rawJson: '{meow: meow}',
    },
    {
      id: 'uuid id 2',
      userId: 'uuid user id 2',
      provider: 'Komoot',
      providerId: 'uuid Komoot 1',
      name: 'Hiking 1',
      sportType: 'Hiking',
      distance: 5032,
      movingTime: 1234567,
      elapsedTime: 1234568,
      elevationGain: 17,
      maxSpeed: 10,
      averageHour: 8,
      maxHour: 10,
      calories: 500,
      date: '20:04 03.08.2026',
      photoUrl: `default_03.avif`,
      visibility: true,
      rawJson: '{meow: meow}',
    },
    {
      id: 'uuid id 3',
      userId: 'uuid user id 3',
      provider: 'Strava',
      providerId: 'uuid Strava 2',
      name: 'Cycling 1',
      sportType: 'Cycling',
      distance: 5032,
      movingTime: 1234567,
      elapsedTime: 1234568,
      elevationGain: 17,
      maxSpeed: 10,
      averageHour: 8,
      maxHour: 10,
      calories: 500,
      date: '20:04 03.08.2026',
      photoUrl: `default_02.jpg`,
      visibility: true,
      rawJson: '{meow: meow}',
    },
    {
      id: 'uuid id 2',
      userId: 'uuid user id 2',
      provider: 'Komoot',
      providerId: 'uuid Komoot 1',
      name: 'Hiking 2',
      sportType: 'Hiking',
      distance: 5032,
      movingTime: 1234567,
      elapsedTime: 1234568,
      elevationGain: 17,
      maxSpeed: 10,
      averageHour: 8,
      maxHour: 10,
      calories: 500,
      date: '20:04 03.08.2026',
      photoUrl: `default_03.avif`,
      visibility: true,
      rawJson: '{meow: meow}',
    },
    {
      id: 'uuid id 3',
      userId: 'uuid user id 3',
      provider: 'Strava',
      providerId: 'uuid Strava 2',
      name: 'Cycling 2',
      sportType: 'Cycling',
      distance: 5032,
      movingTime: 1234567,
      elapsedTime: 1234568,
      elevationGain: 17,
      maxSpeed: 10,
      averageHour: 8,
      maxHour: 10,
      calories: 500,
      date: '20:04 03.08.2026',
      photoUrl: `default_02.jpg`,
      visibility: true,
      rawJson: '{meow: meow}',
    },
    {
      id: 'uuid id 1',
      userId: 'uuid user id 1',
      provider: 'Strava',
      providerId: 'uuid Strava 1',
      name: 'Running 2',
      sportType: 'Running',
      distance: 5032,
      movingTime: 1234567,
      elapsedTime: 1234568,
      elevationGain: 17,
      maxSpeed: 10,
      averageHour: 8,
      maxHour: 10,
      calories: 500,
      date: '20:04 03.08.2026',
      photoUrl: `default_01.webp`,
      visibility: true,
      rawJson: '{meow: meow}',
    },
    {
      id: 'uuid id 3',
      userId: 'uuid user id 3',
      provider: 'Strava',
      providerId: 'uuid Strava 2',
      name: 'Cycling 3',
      sportType: 'Cycling',
      distance: 5032,
      movingTime: 1234567,
      elapsedTime: 1234568,
      elevationGain: 17,
      maxSpeed: 10,
      averageHour: 8,
      maxHour: 10,
      calories: 500,
      date: '20:04 03.08.2026',
      photoUrl: `default_02.jpg`,
      visibility: true,
      rawJson: '{meow: meow}',
    },
    {
      id: 'uuid id 1',
      userId: 'uuid user id 1',
      provider: 'Strava',
      providerId: 'uuid Strava 1',
      name: 'Running 3',
      sportType: 'Running',
      distance: 5032,
      movingTime: 1234567,
      elapsedTime: 1234568,
      elevationGain: 17,
      maxSpeed: 10,
      averageHour: 8,
      maxHour: 10,
      calories: 500,
      date: '20:04 03.08.2026',
      photoUrl: `default_01.webp`,
      visibility: true,
      rawJson: '{meow: meow}',
    },
    {
      id: 'uuid id 2',
      userId: 'uuid user id 2',
      provider: 'Komoot',
      providerId: 'uuid Komoot 1',
      name: 'Hiking 3',
      sportType: 'Hiking',
      distance: 5032,
      movingTime: 1234567,
      elapsedTime: 1234568,
      elevationGain: 17,
      maxSpeed: 10,
      averageHour: 8,
      maxHour: 10,
      calories: 500,
      date: '20:04 03.08.2026',
      photoUrl: `default_03.avif`,
      visibility: true,
      rawJson: '{meow: meow}',
    },
  ];
}
